# Generated by Django 4.2.5 on 2023-11-26 03:45

import Users.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=50)),
                ('middleName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('DOB', models.DateField(validators=[Users.models.isValidDate])),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('password', models.CharField(max_length=20)),
                ('passwordReSetId', models.UUIDField(blank=True , null=True)),
                ('email', models.EmailField(error_messages={'invalid': 'Please enter a valid email address.', 'unique': 'User with this email is already exist'}, max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('phoneNumber', models.CharField(error_messages={'max_length': 'Phone number must have only 10 digits', 'unique': 'User with this phone number is already exist'}, max_length=10, unique=True, validators=[Users.models.isPhoneNumber])),
            ],
        ),
    ]
