# Generated by Django 4.2.5 on 2023-11-26 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='passwordReSetId',
            field=models.UUIDField(),
        ),
    ]
