# Generated by Django 4.2.5 on 2023-11-25 12:03

import Users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='phoneNumber',
            field=models.CharField(default='0', error_messages={'max_length': 'Phone number must have only 10 digit', 'unique': 'User with this number is already exist'}, max_length=10, unique=True, validators=[Users.models.isPhoneNumber]),
        ),
    ]
