# Generated by Django 4.2.5 on 2023-11-26 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_users_passwordresetid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='passwordReSetId',
            field=models.UUIDField(null=True),
        ),
    ]
