# Generated by Django 4.2.5 on 2023-11-26 14:23

import Users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_address_users_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='DOB',
            field=models.DateField(null=True, validators=[Users.models.isValidDate]),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
