# Generated by Django 4.2.5 on 2023-11-26 14:32

import Users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_alter_users_dob_alter_users_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='phoneNumber',
            field=models.CharField(error_messages={'max_length': 'Phone number must have only 10 digits', 'unique': 'User with this phone number is already exist'}, max_length=10, null=True, unique=True, validators=[Users.models.isPhoneNumber]),
        ),
    ]
