# Generated by Django 4.2.5 on 2023-11-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_alter_users_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
