# Generated by Django 4.2.5 on 2023-12-24 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0012_users_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='otp',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
