# Generated by Django 4.2.5 on 2023-12-25 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0013_users_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='lastOtpSentAt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='logo',
            field=models.ImageField(default='UsersImage/default-user.webp', error_messages={'invalid': 'Invalid file (file is not acceptable).'}, max_length=20000, upload_to='UsersImage/'),
        ),
    ]
