# Generated by Django 4.2.5 on 2023-11-30 18:12

import Organization.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0010_alter_users_password'),
        ('Organization', '0003_organization_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(db_index=True, max_length=10, validators=[Organization.models.isRole])),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('OrganizationId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Organization.organization')),
                ('userId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.users')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('checkInTime', models.TimeField()),
                ('checkOutTime', models.TimeField()),
                ('description', models.CharField(error_messages={'invalid': 'Description is too long...'}, max_length=2000)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('OrganizationId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Organization.organization')),
            ],
        ),
    ]
