# Generated by Django 4.2.5 on 2023-12-01 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0011_users_currentactiveorganization'),
        ('Organization', '0005_teammember_teamid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='createAt',
            new_name='createdAt',
        ),
        migrations.AddField(
            model_name='team',
            name='createdBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Users.users'),
        ),
    ]
