# Generated by Django 4.2.5 on 2023-12-06 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0011_users_currentactiveorganization'),
        ('Organization', '0006_rename_createat_team_createdat_team_createdby'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(error_messages={'invalid': 'Please enter a valid job title name.', 'max_length': 'Job title name must be smaller than 100 characters.', 'unique': 'Tile is already exist'}, max_length=100, unique=True)),
                ('Organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Organization.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_employee', to='Users.users')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='Users.users')),
            ],
        ),
    ]
