# Generated by Django 4.2.5 on 2023-12-06 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0011_users_currentactiveorganization'),
        ('Organization', '0007_job_title_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_title',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='job_title',
            name='createdBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.users'),
        ),
        migrations.AddField(
            model_name='job_title',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='createdBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_employee', to='Users.users'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
