# Generated by Django 4.2.5 on 2023-12-06 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0008_job_title_createdat_job_title_createdby_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Organization.organization'),
        ),
    ]
