# Generated by Django 4.2.5 on 2023-12-06 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0009_employee_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='jobTitle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Organization.job_title'),
        ),
    ]
