# Generated by Django 4.2.5 on 2023-12-07 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0011_users_currentactiveorganization'),
        ('Organization', '0010_employee_jobtitle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='createAt',
            new_name='createdAt',
        ),
        migrations.AddField(
            model_name='teammember',
            name='createdBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdBy', to='Users.users'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='userId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='Users.users'),
        ),
    ]
