# Generated by Django 4.2.5 on 2023-12-08 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0011_rename_createat_teammember_createdat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Organization.organization'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='jobTitle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Organization.job_title'),
        ),
    ]
