# Generated by Django 4.2.5 on 2023-12-09 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0011_users_currentactiveorganization'),
        ('Organization', '0012_alter_employee_organization_alter_employee_jobtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaveType', models.CharField(max_length=50, null=True)),
                ('fromDate', models.DateTimeField(max_length=50, null=True)),
                ('toDate', models.DateField(null=True)),
                ('reason', models.CharField(max_length=10000, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True, null=True)),
                ('Organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Organization.organization')),
                ('createdBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.users')),
            ],
        ),
    ]
