# Generated by Django 4.2.5 on 2023-12-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0013_leaverequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(default='Pending', max_length=50, null=True),
        ),
    ]
