# Generated by Django 4.2.5 on 2023-12-09 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0011_users_currentactiveorganization'),
        ('Organization', '0015_alter_leaverequest_fromdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='verifiedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verifiedBy', to='Users.users'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='createdBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaveRequestCreatedBy', to='Users.users'),
        ),
    ]
