# Generated by Django 4.2.5 on 2023-12-10 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0016_leaverequest_verifiedby_alter_leaverequest_createdby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(default='organization.png', error_messages={'invalid': 'Invalid file (file is not acceptable).'}, max_length=16383, upload_to='organizationLogo'),
        ),
    ]
