# Generated by Django 4.2.5 on 2023-12-10 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0017_alter_organization_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(default='organization.png', error_messages={'invalid': 'Invalid file (file is not acceptable).'}, max_length=15000, upload_to='organizationLogo'),
        ),
    ]
