# Generated by Django 4.2.5 on 2023-12-10 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0025_remove_organization_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.FileField(default='organization.png', error_messages={'invalid': 'Invalid file (file is not acceptable).'}, max_length=10000, upload_to=''),
        ),
    ]
