# Generated by Django 4.2.5 on 2023-12-10 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0032_alter_organization_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='TeamId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Organization.team'),
        ),
    ]
