# Generated by Django 4.2.5 on 2023-12-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0034_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='takenAt',
            field=models.DateField(null=True),
        ),
    ]
